development:
  cloud_name: dlprsrrbt
  api_key: '866743919562743'
  api_secret: "NgpMOphRgVnCOSl3Jot-BTDd9q4"
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dlprsrrbt
  api_key: '866743919562743'
  api_secret: "NgpMOphRgVnCOSl3Jot-BTDd9q4"
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dlprsrrbt
  api_key: '866743919562743'
  api_secret: "NgpMOphRgVnCOSl3Jot-BTDd9q4"
  enhance_image_tag: true
  static_file_support: false